apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openerp-prod
resources:
- ../../base
patches:
- target:
    kind: Ingress
    name: openerp
  path: ingress-patch.yaml
commonLabels:
  openerp.env: prod
